// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3pOC8Fgib_82RB2yZCQF8wmtseLCCPqo',
    appId: '1:830768072229:web:c5cf525c71f368a9dc61cc',
    messagingSenderId: '830768072229',
    projectId: 'sichuan-flutter-a93c6',
    authDomain: 'sichuan-flutter-a93c6.firebaseapp.com',
    storageBucket: 'sichuan-flutter-a93c6.firebasestorage.app',
    measurementId: 'G-M92KFX5P3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD94-hpsEeR-DJ96rnn3HSSHPKNuvkXfI8',
    appId: '1:830768072229:android:0bde3930d4d77388dc61cc',
    messagingSenderId: '830768072229',
    projectId: 'sichuan-flutter-a93c6',
    storageBucket: 'sichuan-flutter-a93c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX6xu4TaBUrTVUS4DLXok_l7ZV94NkUY4',
    appId: '1:830768072229:ios:cb3c1616d3f053dddc61cc',
    messagingSenderId: '830768072229',
    projectId: 'sichuan-flutter-a93c6',
    storageBucket: 'sichuan-flutter-a93c6.firebasestorage.app',
    iosBundleId: 'com.koofy.sichuan',
  );

}